---
Name: form-validation
---
SilverStripe\Forms\Form:
  extensions:
    - Innoweb\FormValidation\Forms\Extensions\FormExtension

SilverStripe\Forms\FormField:
  extensions:
    - Innoweb\FormValidation\Forms\Extensions\FormFieldExtension
